include:
 - project: acc-co/devops/python/acc-py-devtools
   file: acc_py_devtools/templates/gitlab-ci/python.yml

variables:
  project_name: cernml.coi


# A full installation of the package, tested with pytest.
test_install:
  extends: .acc_py_full_test
  script:
      - mkdir -p not-the-source-dir
      - cp examples/parabola.py ./not-the-source-dir/
      - cd ./not-the-source-dir
      - python -c "import ${project_name}"
      - python ./parabola.py opt
      - python ./parabola.py rl


# A development installation of package, tested with pytest.
test_dev:
  extends: .acc_py_dev_test
  script:
      - pytest ${project_root}/tests --cov=${project_name} --junitxml=report.xml


# A push of the source distribution to the acc-py PyPI, only on git tag.
release_sdist_on_tag:
  extends: .acc_py_release_sdist
