[build-system]
requires = [
    "setuptools >= 45",
    "setuptools-scm[toml] ~= 7.0",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.black]
target-version = ['py37', 'py38']
include = '\.pyi?$'

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "--doctest-modules"
testpaths = ["tests", "cernml"]

[tool.pylint.MASTER]
extension-pkg-whitelist = "PyQt5"

[tool.pylint.FORMAT]
ignore-long-lines = '<?https?://\S+>?$'

[tool.pylint.REPORTS]
reports = false
score = false

[tool.pylint."MESSAGES CONTROL"]
disable = ["similarities", "fixme"]
